services:
  vondbot:
    build: ./vondbot
    env_file:
      - .env
  vonied:
    build: ./vonied
  vonapi:
    build: ./vonapi
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
